version: '3'
services:
  frontend:
    build: https://github.com/4649AP/ds_example.git#master:frontend
    entrypoint: python3
    command: app.py
    ports:
     - "5001:5000"

  backend:
    build: https://github.com/4649AP/ds_example.git#master:backend
    entrypoint: python3
    command: app.py
    ports:
     - "5000:5000"
    tty: true